apiVersion: v1
kind: Service
metadata:
  name: wishlists-db
  labels:
    app: wishlists-db
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: wishlists-db
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
