name: CI Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.12-slim

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python package dependencies
        run: |
          python -m pip install -U pip pipenv
          pipenv install --system --dev

      - name: Linting
        run: make lint

      - name: Run tests with coverage
        run: pytest --pspec --cov=service --cov-fail-under=95 --cov-report=xml --disable-warnings
        env:
          DATABASE_URI: postgresql+psycopg://postgres:postgres@postgres:5432/postgres

      - name: Install packages for Codecov to work
        run: apt-get update && apt-get install -y git curl gpg

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true
